Incorrect pr again

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -12,3 +12,15 @@ jobs:
 
     - name: clang-tidy review
       uses: ZedThree/clang-tidy-review@v0.7.0
+
+      id: review
+
+      # If there are any comments, fail the check
+    - name: Passed C++ style guide checks  
+      #if: steps.review.outputs.total_comments > 0
+      #run: exit 1
+      run: |
+        echo "num_comments = ${{steps.review.outputs.total_comments}}"
+        if [ steps.review.outputs.total_comments > 0 ]; then
+          exit 1
+        fi  
